-- ROLLBACK: Disable RLS policies
-- Run this if you need to revert the RLS changes
-- WARNING: This will disable security on all tables!

-- User tables
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_profile DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_badge DISABLE ROW LEVEL SECURITY;

-- User activity
ALTER TABLE IF EXISTS restaurant_stamps DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS checkin DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS favorite DISABLE ROW LEVEL SECURITY;

-- Gamification
ALTER TABLE IF EXISTS xp_event DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS user_quest DISABLE ROW LEVEL SECURITY;

-- Drops
ALTER TABLE IF EXISTS daily_drop_claims DISABLE ROW LEVEL SECURITY;

-- Trails
ALTER TABLE IF EXISTS trail_step_completions DISABLE ROW LEVEL SECURITY;

-- Social
ALTER TABLE IF EXISTS video_likes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS video_events DISABLE ROW LEVEL SECURITY;

-- Referrals
ALTER TABLE IF EXISTS referral_code DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS referral_claim DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS referral_events DISABLE ROW LEVEL SECURITY;

-- Events
ALTER TABLE IF EXISTS app_events DISABLE ROW LEVEL SECURITY;

-- Public tables
ALTER TABLE IF EXISTS city DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS restaurant DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS restaurant_images DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS list DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS list_entry DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS badge DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS quest DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS trails DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS trail_steps DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS daily_drops DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS videos DISABLE ROW LEVEL SECURITY;

-- Note: Policies will remain but won't be enforced with RLS disabled

